Linux
AlexSmith/hoshie-lang pull request #4
Opened 2022-04-04 20:36 UTC by AlexSmith

Bringing in the changes to package.json so it works accross a select few operating systems.
also changing the generate funciton to returna boolean value True: if a file is being genrated and False if a file isnt being generated
this is used in index.ts to stop files that do not need to be compiled from being run it will also remove a previously compiled version of the file that isnt being compiled if it exists.

2022-04-04 20:50 UTC, AhernEYeldarB requested changes
*.backup files don't need to be committed also

2022-04-04 20:50 UTC, AhernEYeldarB commented on src/hlcc/codeGen/js.ts
> +            fs.mkdirSync(path.dirname(jsPath), { recursive: true });
```suggestion
            fs.mkdirSync(path.dirname(jsPath), { recursive: true });
```

2022-04-04 20:50 UTC, AhernEYeldarB commented on src/hlcc/codeGen/js.ts
> +    return true;
```suggestion
export function generate(hlFile: HLFileScope):boolean {
    if(!hlFile.allActions().length ) return;
    const jsWriter = new JSWriter();
    hlFile.allActions().forEach(row => {
        jsWriter.writeAction(row);
    });
    jsWriter.output();
```
We can then check hlFile.text truthy to know if a file is to be written as to not have ambiguous true or false returns

2022-04-04 20:50 UTC, AhernEYeldarB commented on src/index.ts
> +            break; };
This could all be added to a util
```
function cleanExistingFile(filePath: string) {
    if(!existsSync(filePath)) return;
    unlinkSync(filePath);
}
```

Which can be called like this 
```suggestion
        const filePath = outPath(argv.file);
        if (!!!hlFile.text) { 
            cleanExistingFile(filePath);
            break;
        }
```

 Its easier to follow what is happening this way I think. Adding `filePath` to a `const` variable because it is used a couple of times and doesnt need to be recalculated.

We wont have ambiguous true and false statements that way. 

IE what does it mean for `generate` to be true or false VS IF we have no text clean everything up

2022-04-04 20:50 UTC, AhernEYeldarB commented on tutorial/080-library.ho
> +export mol = 42;
```suggestion
export mol = 42;

```

2022-04-04 20:56 UTC, AhernEYeldarB commented
solves https://github.com/AlexSmith/hoshie-lang/issues/2

2022-04-04 21:50 UTC, AhernEYeldarB commented on .gitignore
> +*.vsix
```suggestion
*.vsix

```

2022-04-04 21:50 UTC, AhernEYeldarB commented on .gitignore
> +tutorial/out-js/
think this should be file names not a dir file
```suggestion
tutorial/out-js.*
```
https://github.com/AlexSmith/hoshie-lang/blob/62cd2fdbab0e51990087123ec0199180dd406670/src/hlcc/codeGen/js.ts#L18

2022-04-05 11:29 UTC, AlexSmith commented on .gitignore
> +*.vsix
White space addition only.

2022-04-05 11:31 UTC, AlexSmith commented on .gitignore
> +tutorial/out-js/
It will ignore everything inside out-js,
The proposed changed would only ignore files inside tutorial that are named out-js with any file extension 
"out-js.*"

2022-04-05 11:34 UTC, AhernEYeldarB approved these changes
:THIS:

2022-04-05 11:34 UTC, AlexSmith commented on src/index.ts
> +            break; };
Agreed, generate having a Boolean response to represent an atomic issue is ambiguous. 
A util function would be prefered.

2022-04-05 12:20 UTC, AlexSmith commented on src/hlcc/cst/scope.ts
> +        if (this._actions.length == 0){
yep enforcing type is important.

2022-04-06 13:53 UTC, GordonSmith requested changes
Some minor comments

2022-04-06 13:53 UTC, GordonSmith commented on src/hlcc/codeGen/js.ts
> +    if(fs.existsSync(outPath(hlFile.path))){fs.unlinkSync(outPath(hlFile.path));}
Turn on "auto format on save" in vscode (tends to be the default for TS developers).

2022-04-06 13:53 UTC, GordonSmith commented on src/hlcc/cst/scope.ts
> +        return true;
Minor:  `return this._actions.length > 0;` would be cleaner.

2022-04-06 13:53 UTC, GordonSmith commented on src/hlcc/cst/scope.ts
> +    }
Minor: return this._errors.length > 0; would be cleaner.

2022-04-06 14:43 UTC, GordonSmith approved these changes
There are a few stray `;` in there, but adding a linter would catch those and others...

2022-04-06 14:43 UTC, GordonSmith commented on src/hlcc/codeGen/js.ts
> +    };
Minor:  No semicolon needed (a linter will auto fix this type of issue for you)

2022-04-06 15:11 UTC, merged